import org.gradle.api.plugins.quality.CodeNarcExtension

plugins {
    id 'groovy'
    id 'java-gradle-plugin'
    id("com.gradle.plugin-publish") version "1.2.1"
    id 'codenarc'
}


dependencies {
    codenarc 'org.codenarc:CodeNarc:3.6.0-groovy-4.0'
}


extensions.configure(CodeNarcExtension) {
    it.configFile = file('config/codenarc/codenarc.groovy')
    it.maxPriority1Violations = 0
    it.maxPriority2Violations = 0
    it.maxPriority3Violations = 0
}


group = rootProject.group
version = "0.1.0"


repositories {
    mavenCentral()
}


gradlePlugin {
    website = "https://github.com/qishr/cascara-build-logic"
    vcsUrl = "https://github.com/qishr/cascara-build-logic"
    plugins {
        sharedConventions {
            id = "io.github.qishr.cascara-meta.publish"
            implementationClass = "PublishPlugin"
            displayName = "Cascara Publishing Conventions"
            description = "Shared Publishing conventions for Cascara projects"
            tags = ["artifact-signing", "release-setup", "metadata-configuration", "version-coordination", "artifact-structure"]
        }
    }
}
